### ISSUE TITLE
Add support for type casting

### ISSUE THREAD

**Issue by sstur** [asmblah/uniter#13]
Support syntax like:

    $str = (string)$num;

**Comment by asmblah** [comment]
Hi @sstur,

Over a year late now I know, but I've now added support for the `(array)...`, `(binary)...`, `(bool)...`, `(float)...`, `(int)...`, `(object)...` `(string)...` and `(unset)...` casts to Uniter v2.6.0/PHPToAST v3.3.1/PHPToJS v3.1.0/PHPCore v3.6.0/PHPRuntime v4.1.0.

All the best,
Dan

**Comment by sstur** [comment]
Oh, awesome! I was using this library last year to test my js2php in the browser (so it was js -> php -> js : )
