### ISSUE TITLE
Optional "public" keyword on methods

### ISSUE THREAD

**Issue by sstur** [asmblah/uniter#15]
Support methods with public/private keyword omitted (default to public):

    class Thing {
      function f() { /* public method */ }
    }

**Comment by asmblah** [comment]
Hi @sstur,

I've now added support for omitting method visibility in Uniter v1.0.0.

Cheers!
Dan

**Comment by asmblah** [comment]
Hi @sstur,

I hope you don't mind if I close this issue now as it's been open for a while. If this fix didn't work for you, please feel free to open it again.

Cheers,
Dan
