### ISSUE TITLE
Heredoc/Nowdoc

### ISSUE THREAD

**Issue by IngwiePhoenix** [asmblah/uniter#34]
``` php
<?php
$txt = <<<EOT
bar
EOT;
```

and 

``` php
<?php
$name = "Bob";
$txt = <<<-'EOT'
{$name}'s bar
EOT;
```

dont work. :)

Just a heads up! I might got the second - Nowdoc - wrong. But you probably know what I meant...

**Comment by asmblah** [comment]
Thanks for raising this @IngwiePhoenix - you're right, I haven't implemented heredoc/nowdoc just yet.

**Comment by asmblah** [comment]
Heredoc and nowdoc support have been available for a while now - closing. Hope all is good with you @IngwiePhoenix!
