### ISSUE TITLE
Using uniter name in a domain

### ISSUE THREAD

**Issue by phpengine** [asmblah/uniter#44]
Hi,

I made two sites with the Uniter name in the title. One is www.uniterjquery.org.uk and one is www.theuniterleague.org.uk. Is that OK?

Any ideas for better names than the above? The first one seems fine but the second one might not be clear to everyone that might use it.

**Comment by asmblah** [comment]
Hi @phpengine - yes, those will be fine, thank you for asking!

The second one seems fine to me - the only alternative that springs to mind would be something along the lines of "Friends of Symfony" (https://github.com/FriendsOfSymfony) ie. "Friends of Uniter", but I'm not sure that's any better to be honest.

**Comment by asmblah** [comment]
Closing this issue as it all seems fine to me.
