### ISSUE TITLE
Switch Order different

### ISSUE THREAD

**Issue by chipshort** [asmblah/uniter#61]
The following code works differently on uniter compared to actual php:

```php
switch ('PATCH') {
    default:
        return 'uniter return';
    case 'PATCH':
        return 'php return';
}
```

When running this on the official php runtime, it returns `'php return'`, while on uniter, it returns `'uniter return'`.

**Comment by asmblah** [comment]
Thanks for raising this @chipshort - apologies for the delay, I intend to have a fix out soon.

I realise 8 days have passed now, but how urgent is this issue for you?

**Comment by chipshort** [comment]
Hi, no worries. For me this is not urgent at all, I implemented a workaround for my specific use case.
I just wanted to report this, so it can be fixed at some point.

Thanks for the cool libraries btw.

**Comment by asmblah** [comment]
You're very welcome @chipshort - the fixes referenced above should go out in the next release once ready (which should be within the next week or so).

**Comment by asmblah** [comment]
@chipshort apologies for the super-long delay, but a fix for this has now gone out in the latest release.

**Comment by chipshort** [comment]
No worries, thanks for the work you do and for this awesome package!
I don't have access to the project where I needed this anymore, but the test in the PR looks good, so I think this issue can be closed.

**Comment by asmblah** [comment]
You're very welcome @chipshort.
