### ISSUE TITLE
Online REPL

### ISSUE THREAD

**Issue by jcubic** [asmblah/uniter#72]
I'm just checking all examples on the [jQuery Terminal](https://terminal.jcubic.pl) website. And found my old Codepen demo that got some views and likes.

I decided to share, just in case you may want to use it, or link to the demo from README.

https://codepen.io/jcubic/pen/VGYBVj?editors=0010

On Codepen anyone can easily experiment with the project and they get REPL for free.

If you like the idea of linking from README, I'm happy to create a PR.

**Comment by asmblah** [comment]
Hey @jcubic, thanks for this. Sure, I'd be happy to link to this from the README if you'd like to create a PR. Apologies for not getting back to you sooner.

Cheers!

**Comment by asmblah** [comment]
Closing now that https://github.com/asmblah/uniter/pull/73 has been merged. Thanks again @jcubic!
