### ISSUE TITLE
Can I run uniter through the "script" tag?

### ISSUE THREAD

**Issue by katetem** [asmblah/uniter#9]
Also I want to load the script through "src" attribute so I can separate the script.

**Comment by asmblah** [comment]
Hi @katetem,

Sorry I never got back to you on this. I've just tagged v0.2.2 with Browserify support, and I've included a pre-built bundle of the core in the `dist/` folder, so in your case you should be able to just include with `<script src="<your-path>/dist/uniter.js"></script>` and then access the `uniter` global variable.

Hope this helps!
Dan

**Comment by asmblah** [comment]
Hi @katetem,

I'm closing this issue as it's been open for a while now. If you still have a question, feel free to open it again.

Cheers,
Dan
